version: "3"
services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:latest
    ports:
      - "1337:1337"
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always