name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      TOKENTEST: ${{ secrets.TOKENTEST }}
      GUILDID: ${{ secrets.GUILDID }}
      APEXMAPTOKEN: ${{ secrets.APEXMAPTOKEN }}
      DATABASETOKEN: ${{ secrets.DATABASETOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ secrets.DOCKER_USERNAME }}/waifubot:latest
          build-args: |
            TOKEN=${{ secrets.TOKEN }}
            TOKENTEST=${{ secrets.TOKENTEST }}
            GUILDID=${{ secrets.GUILDID }}
            APEXMAPTOKEN=${{ secrets.APEXMAPTOKEN }}
            DATABASETOKEN=${{ secrets.DATABASETOKEN }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DOCKER_REPO=${{ secrets.DOCKER_REPO }}
            DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}
          